### ISSUE TITLE
Error: xDebugToggler.app will damage your computer

### ISSUE THREAD

**Issue by wakebit** [deligoez/xDebug-Toggler#3]
The program has stopped working today.

When I'm trying to run it, Mac OS shows error:
"**xDebugToggler.app will damage your computer. You should move it to the Bin.**".

In the _System Preferences_ > _Security & Privacy_ > _General_ this app doesn't shown as locked. Option '_Allow apps download from AppStore and identified developers_' enabled.

OS references to some malware and shows option for report it to Apple only.

Mac OS Big Sur 11.0.1, PHP 7.4.

**Comment by wakebit** [comment]
@deligoez Help, please.

**Comment by deligoez** [comment]
Hej @shtoffeine, I've added more details about opening the app on the readme section.
